name: Push Docker Image

on:
  push:
    branches: [ master ]
    
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest

    env:
      IMAGE: monitor-bot

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to private registry
      uses: docker/login-action@v2
      with:
        registry: mckismetlab.net
        username: ${{ secrets.MCKISMETLAB_DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.MCKISMETLAB_DOCKER_REGISTRY_PASSWORD }}

    - name: Build the Docker image And Push
      id: firs-docker-pull
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_STORAGE_IP }}/${{ env.IMAGE }}
      continue-on-error: true

    - name: Retry again on failure Build the Docker image And Push
      id: second-docker-pull
      if: steps.firs-docker-pull.outcome != 'success'
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_STORAGE_IP }}/${{ env.IMAGE }}

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}/monitor-bot-build-webhook
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        webhook_auth: ${{ secrets.WEBHOOK_USERNAME }}:${{ secrets.WEBHOOK_PASSWORD }}
