name: Push Docker Image

on:
  push:
    branches: [ master ]
    
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 220.134.105.30:56125/monitor-bot:$(date +%s)
    - name: Docker Push
      run: docker push 220.134.105.30:56125/monitor-bot:$(date +%s)
